# Generated by Django 6.0.6 on 2026-07-06 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brgy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='id_back',
            field=models.ImageField(blank=True, null=True, upload_to='resident_ids/'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='id_front',
            field=models.ImageField(blank=True, null=True, upload_to='resident_ids/'),
        ),
    ]
