# Generated by Django 6.0.6 on 2026-07-11 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brgy', '0002_customuser_id_back_customuser_id_front'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documenttype',
            name='fee',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
    ]
