# Generated by Django 6.0.6 on 2026-07-30 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brgy', '0005_customuser_profile_picture_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='barangay',
            name='theme_color',
            field=models.CharField(default='#4F46E5', help_text='Hex color for barangay theme (e.g. #4F46E5)', max_length=7),
        ),
    ]
