# Generated by Django 6.0.6 on 2026-08-03 08:04

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brgy', '0006_barangay_theme_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentrequest',
            name='document_type',
        ),
        migrations.AddField(
            model_name='documentrequest',
            name='contact_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='documentrequest',
            name='pickup_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='DocumentRequestItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brgy.documenttype')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='brgy.documentrequest')),
            ],
        ),
    ]
