# Generated by Django 6.0.6 on 2026-08-10 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brgy', '0007_remove_documentrequest_document_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentrequest',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='documentrequest',
            name='ready_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
