# Generated by Django 6.0.6 on 2026-08-12 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brgy', '0008_documentrequest_approved_at_documentrequest_ready_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='id_selfie',
            field=models.ImageField(blank=True, help_text='Picture of the user holding their valid ID', null=True, upload_to='resident_ids/'),
        ),
    ]
