# Generated by Django 6.0.6 on 2026-08-23 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brgy', '0009_customuser_id_selfie'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentrequest',
            name='verification_code',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
