# Generated by Django 6.0.6 on 2026-07-20 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brgy', '0004_remove_customuser_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures/'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='rejection_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='documenttype',
            name='template_file',
            field=models.FileField(blank=True, help_text='Upload a .docx template for this document', null=True, upload_to='document_templates/'),
        ),
    ]
